name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"

      - name: Bump Version and Create Tag
        id: versioning
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          if [ -z "$latest_tag" ]; then
            new_tag="v1.0.0"
          else
            new_tag=$(echo $latest_tag | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          fi
          echo "Creating new tag: $new_tag"
          git tag $new_tag
          echo "::set-output name=new_tag::$new_tag"

      - name: Push Tag to GitHub
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git push origin ${{ steps.versioning.outputs.new_tag }}

      - name: Install git-changelog
        run: pip install git-changelog

      - name: Generate Changelog
        id: changelog
        run: |
          latest_tag=${{ steps.versioning.outputs.new_tag }}
          git-changelog -t ${latest_tag}..HEAD -s > RELEASE_NOTES.md

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ steps.versioning.outputs.new_tag }}
          release_name: Release ${{ steps.versioning.outputs.new_tag }}
          body_path: ./RELEASE_NOTES.md
          draft: false
          prerelease: false
