name: Snyk Code Test

on:
  push:
    branches:
      - main

jobs:
  snyk-code-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Install dependencies
      run: npm install

    - name: Run Snyk code test
      run: snyk code test --sarif > snyk-code.sarif

    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk-code.sarif
